# Generated by Django 6.0.3 on 2026-04-07 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256, verbose_name='Nome completo do usuário')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='E‑mail único por usuário')),
                ('regiao', models.CharField(choices=[('NORTE 1', 'NORTE 1'), ('NORTE 2', 'NORTE 2'), ('LESTE 1', 'LESTE 1'), ('LESTE 2', 'LESTE 2'), ('SUL', 'SUL'), ('SUDESTE', 'SUDESTE'), ('SUDOESTE', 'SUDOESTE'), ('OESTE', 'OESTE'), ('CENTRO', 'CENTRO'), ('REGIAO METROPOLITANA', 'REGIAO METROPOLITANA')], max_length=30, verbose_name='Região')),
                ('cidade', models.CharField(default='São Paulo', max_length=50)),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='Senha')),
                ('moderador', models.BooleanField(db_column='moderador', default=False)),
                ('administrador', models.BooleanField(db_column='administrador', default=False)),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador único do livro')),
                ('cod_api', models.IntegerField(blank=True, null=True, verbose_name='Código de integração com API externa')),
                ('estado', models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('NORMAL', 'Normal'), ('DANIFICADO', 'Danificado')], max_length=10, verbose_name='Estado de conservação do livro')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para troca/empréstimo')),
                ('em_doacao', models.BooleanField(default=False, verbose_name='Disponível para doação')),
                ('id_dono', models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono do livro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador único da troca')),
                ('data_troca', models.DateField(default=django.utils.timezone.now, verbose_name='Data da troca')),
                ('id_dono', models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_dono', to=settings.AUTH_USER_MODEL, verbose_name='Dono do livro')),
                ('id_interessado', models.ForeignKey(db_column='id_interessado', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_interessado', to=settings.AUTH_USER_MODEL, verbose_name='Interessado no livro')),
                ('id_livro', models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro', verbose_name='Livro em transação')),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'db_table': 'troca',
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Quando o interesse foi registrado')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário interessado')),
                ('id_livro', models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro', verbose_name='Livro de interesse')),
            ],
            options={
                'verbose_name': 'Interesse',
                'verbose_name_plural': 'Interesses',
                'db_table': 'interesses',
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_livro'), name='unique_interesse')],
            },
        ),
    ]
