# Generated by Django 6.0.4 on 2026-04-24 04:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da capa'),
        ),
        migrations.AddField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopse'),
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rating',
            field=models.FloatField(blank=True, help_text='Avaliação de 0 a 5 estrelas. Se nulo, significa não avaliado.', null=True, verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='cod_api',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OLID (OpenLibrary ID)'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível para troca'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('NORMAL', 'Normal'), ('DANIFICADO', 'Danificado')], max_length=10, verbose_name='Estado de conservação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id_dono',
            field=models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='regiao',
            field=models.CharField(choices=[('NORTE 1', 'NORTE 1'), ('NORTE 2', 'NORTE 2'), ('LESTE 1', 'LESTE 1'), ('LESTE 2', 'LESTE 2'), ('SUL', 'SUL'), ('SUDESTE', 'SUDESTE'), ('SUDOESTE', 'SUDOESTE'), ('OESTE', 'OESTE'), ('CENTRO', 'CENTRO'), ('REGIAO METROPOLITANA', 'REGIAO METROPOLITANA')], max_length=30, verbose_name='Região na cidade de São Paulo'),
        ),
    ]
