# Generated by Django 6.0.4 on 2026-04-24 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0002_livro_autor_livro_capa_url_livro_sinopse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca',
            name='avaliacao_dono',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação do dono sobre o interessado'),
        ),
        migrations.AddField(
            model_name='troca',
            name='avaliacao_interessado',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação do interessado sobre o dono'),
        ),
        migrations.AddField(
            model_name='troca',
            name='comentario_dono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='comentario_interessado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
